-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Availabilities"
(
    "PharmacyId" integer NOT NULL,
    "DrugId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UpdatedAt" date NOT NULL,
    CONSTRAINT "Availability_pkey" PRIMARY KEY ("PharmacyId", "DrugId")
);

CREATE TABLE IF NOT EXISTS public."Drugs"
(
    "Id" integer NOT NULL,
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Price" numeric(10, 2) NOT NULL,
    "ManufacturerId" integer NOT NULL,
    CONSTRAINT "Drug_pkey" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Pharmacies"
(
    "Id" integer NOT NULL,
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Adress" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Pharmacy_pkey" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Phones"
(
    "Id" integer NOT NULL,
    "Name" character varying(20) NOT NULL,
    "PharmacyId" integer NOT NULL,
    "PhoneTypeId" integer NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."PhoneTypes"
(
    "Id" integer NOT NULL,
    "Name" character varying(20) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Manufacturers"
(
    "Id" integer NOT NULL,
    "Name" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public."Availabilities"
    ADD CONSTRAINT drug_fkey FOREIGN KEY ("DrugId")
    REFERENCES public."Drugs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Availabilities"
    ADD CONSTRAINT pharmacy_fkey FOREIGN KEY ("PharmacyId")
    REFERENCES public."Pharmacies" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Drugs"
    ADD CONSTRAINT "ManufacturerId" FOREIGN KEY ("ManufacturerId")
    REFERENCES public."Manufacturers" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Phones"
    ADD CONSTRAINT "PharmacyId" FOREIGN KEY ("PharmacyId")
    REFERENCES public."Pharmacies" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Phones"
    ADD CONSTRAINT "PhoneTypeId" FOREIGN KEY ("PhoneTypeId")
    REFERENCES public."PhoneTypes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;