-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Pharmacy"
(
    pharmacy_id integer NOT NULL,
    name character varying(100) NOT NULL,
    adress character varying(200) NOT NULL,
    phone character varying(20) NOT NULL,
    PRIMARY KEY (pharmacy_id),
    CONSTRAINT phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public."Drug"
(
    drug_id integer NOT NULL,
    name character varying(100) NOT NULL,
    manufacturer character varying(100) NOT NULL,
    price numeric(10, 2) NOT NULL,
    PRIMARY KEY (drug_id)
);

CREATE TABLE IF NOT EXISTS public."Availability"
(
    pharmacy_id integer NOT NULL,
    drug_id integer NOT NULL,
    quantity integer NOT NULL,
    updated_at date NOT NULL,
    PRIMARY KEY (pharmacy_id, drug_id)
);

ALTER TABLE IF EXISTS public."Availability"
    ADD CONSTRAINT pharmacy_fkey FOREIGN KEY (pharmacy_id)
    REFERENCES public."Pharmacy" (pharmacy_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Availability"
    ADD CONSTRAINT drug_fkey FOREIGN KEY (drug_id)
    REFERENCES public."Drug" (drug_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;